# Generated by Django 2.2.3 on 2019-07-10 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default=None, max_length=240, null=True)),
                ('cook_time', models.CharField(max_length=4)),
                ('servings', models.CharField(max_length=10)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_file', models.TextField(blank=True, default=None, null=True)),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
